### ISSUE TITLE
Match uri returns nil with query params

### ISSUE THREAD

**Issue by colindresj** [aroemers/sibiro#3]
The following occurs for me:

``` clj
(require '[sibiro.core :as s])
;; => nil
(def routes (s/compile-routes #{[:get "/my-route" :my-route]}))
;; => #'user/routes
(s/path-for routes :my-route {:q "abc"})
;; => "/my-route?q=abc"
(s/match-uri routes *1 :get)
;; => nil
(s/path-for routes :my-route)
;; => "/my-route"
(s/match-uri routes *1 :get)
;; => {:route-handler :my-route, :route-params {}, :alternatives ()}
```

I expected routes to match regardless of query string. I'm able to get around this by stripping the query string before matching, but it took me a bit to realize.

**Comment by aroemers** [comment]
Hi @colindresj,

You could use `uri-for` instead of `path-for`, as the latter is simply a utility function wrapping the former. The following would work:

``` clj
(s/uri-for routes :my-route {:q "abc"})
;; => {:uri "/my-route", :query-string "?q=abc"}
(s/match-uri routes (:uri *1) :get)
;; => {:route-handler :my-route, :route-params {}, :alternatives ()}
```

Of course, I could add the stripping of the query string in the `match-uri` implementation, but in most cases this is not needed and would impose unnecessary processing power.

Does above `uri-for` usage help you enough?

**Comment by colindresj** [comment]
I was actually using `path-for` just for illustration purposes. The real problem for me is that I have a url, `/home`, and sometimes the request will come through with query params, like `/home?utm_campaign=holiday%20campaign`. When that query string exists, I'm not ending up on my homepage as I would expect.

I can see why you would't want to match on a query string, but it wasn't clear to me that that was the case until after a bit of digging.

In the ring world, doesn't seem to be too much of a problem because of middleware, but I got tripped up in the browser, where I found myself trying to match directly on the event token during browser navigation, not realizing that the token included the query string.

**Comment by aroemers** [comment]
I see now. Is there something sibiro, its documentation or I can do for you in this regard?

**Comment by colindresj** [comment]
I think just a note in the `match-uri` section of the readme would help

**Comment by aroemers** [comment]
I have added the note, thank you for the tip @colindresj, closing the issue now.
